@baseUrl = http://192.168.130.142:3000/
@arenaId = JYY-WYY-YYYK
@playerId = 4e7db76c-81ff-4226-a0c6-ed1fba8e6090

get {{baseUrl}}public-arenas

###

get {{baseUrl}}development/arena/{{arenaId}}/state

###

get {{baseUrl}}arena/{{arenaId}}/settings

###

post {{baseUrl}}arena/create
Content-Type: application/json

{
    "arenaType": "development",
    "countdownToStart": 100,
    "gameLength": 42000,
    "players": []
}

###

post {{baseUrl}}arena/{{arenaId}}/create-players
Content-Type: application/json

{
    "sharkName": "RxJShark"
}

###
delete {{baseUrl}}arena/{{arenaId}}/remove-player/{{playerId}}

###

put {{baseUrl}}development/tweak
Content-Type: application/json

{
    "arenaId": "{{arenaId}}",
    "maxDeathTimePenalty": 12,
    "torpedoRegenFrequency": 1,
    "laserEnergyToll": 0,
    "laserHitHealthToll": -1,
    "maxEnergy": 100,
    "maxHealth": 2000,
    "pointsPerLivingBeat": 1
}