@baseUrl = http://192.168.130.142:3000/
@arenaId = VYY-XYY-YYYB
@playerId = f36ff446-96f8-4c91-bb46-cdc75476d0dd
@sharkId = 0000-0008

get {{baseUrl}}public-arenas

###

get {{baseUrl}}development/arena/{{arenaId}}/state

###

get {{baseUrl}}arena/{{arenaId}}/settings

###

post {{baseUrl}}arena/create
Content-Type: application/json

{
    "arenaType": "development",
    "countdownToStart": 100,
    "gameLength": 42000,
    "players": []
}

###

post {{baseUrl}}arena/{{arenaId}}/create-players
Content-Type: application/json

{
    "sharkName": "RxJShark"
}

###
delete {{baseUrl}}arena/{{arenaId}}/remove-player/{{playerId}}

###

put {{baseUrl}}development/tweak
Content-Type: application/json

{
    "arenaId": "{{arenaId}}",
    "maxDeathTimePenalty": 12,
    "torpedoRegenFrequency": 1,
    "laserEnergyToll": 0,
    "laserHitHealthToll": -1,
    "maxEnergy": 60,
    "maxHealth": 100,
    "pointsPerLivingBeat": 1
}

###

post {{baseUrl}}development/marker
Content-Type: application/json

{
    "arenaId": "{{arenaId}}",
    "lifeSpan": 1000,
    "x": 50,
    "y": 550
}

###

post {{baseUrl}}development/marker
Content-Type: application/json

{
    "arenaId": "{{arenaId}}",
    "lifeSpan": 100000,
    "x": 750,
    "y": 550
}

###
put {{baseUrl}}development/sharks/position
Content-Type: application/json

{
    "arenaId": "{{arenaId}}",
    "sharks": [
        {
            "sharkId": "{{sharkId}}",
            "centerPointX": 50,
            "centerPointY": 50,
            "facingAngle": 4.36
        }
    ]
}
